Updated CI and fixed linting error with Bash code.

diff --git a/.github/workflows/validate-config.yml b/.github/workflows/validate-config.yml
--- a/.github/workflows/validate-config.yml
+++ b/.github/workflows/validate-config.yml
@@ -6,8 +6,11 @@ jobs:
   validate_config:
     runs-on: ubuntu-latest
 
+    env:
+      PYTHONDEVMODE: 1
+
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v6
 
       - name: BOM check
         run: |
@@ -16,7 +19,14 @@ jobs:
       - name: Validate file extensions
         run: |
           set -o pipefail
-          ls -1 ispdb/ | grep -v '\.xml$' | awk '{print "::error file=ispdb/"$0"::File name \"ispdb/"$0"\" does not end in .xml – Please rename!"}' && exit 1 || true
+          shopt -s extglob nullglob
+          files=( ispdb/!(*.xml) )
+          if (( ${#files[*]} )); then
+              for file in "${files[@]}"; do
+                  printf '::error file=%s::File name "%s" does not end in .xml – Please rename!\n' "$file" "$file"
+              done
+              exit 1
+          fi
 
       - name: Validate XML content
         run: |
